
patches:
- target:
    version: v1
    kind: Pod
    name: helloworld
  patch: |-
    - op: replace
      path: /spec/containers/0/args
      value: ["/bin/echo This is an overwrite from Kustomize."]
    - op: replace
      path: /spec/containers/1/args
      value: ["/bin/echo This is a 2nd overwrite from Kustomize."]
resources:
- templates/pod.yaml
- templates/pod-2.yaml